### ISSUE TITLE
Add Acala

### ISSUE THREAD

**Issue by xlc** [kudos-ink/project-classification#138]
### Project Name

Acala

### Slug

Acala

### Description

Acala is building the liquidity layer for web3 finance that is captive and sustainable.

### Websites

https://acala.network

### Documentation

https://wiki.acala.network

### Explorers

https://acala.subscan.io

### Repositories

Runtime - https://github.com/AcalaNetwork/Acala
Node - https://github.com/AcalaNetwork/acala-node
SDK - https://github.com/AcalaNetwork/acala.js
EVM SDK - https://github.com/AcalaNetwork/bodhi.js
Chopsticks - https://github.com/AcalaNetwork/chopsticks
ORML - https://github.com/open-web3-stack/open-runtime-module-library

### Social Media

X - https://x.com/AcalaNetwork/
Discord - https://discord.gg/xZfRD6rVfJ
LinkedIn - https://www.linkedin.com/company/acalanetwork

### Networks

Polkadot

### Purposes

- [ ] ai
- [ ] bridge
- [ ] dao
- [ ] data
- [X] defi
- [X] evm
- [ ] gaming
- [ ] governance
- [ ] nft
- [ ] oracles
- [ ] rwa
- [ ] socialfi
- [X] staking
- [ ] testing
- [ ] universal

### Stack Levels

- [X] protocol
- [X] runtime
- [ ] smart-contract
- [ ] messaging
- [ ] offchain

### Technologies

Substrate

### Types

- [X] platform
- [X] tool
- [X] library
- [ ] client
- [ ] framework
- [ ] template
- [ ] mobile
- [ ] service
- [ ] dApp

### Rewards

- [ ] The project can pay rewards to contributors.

**Comment by CJ13th** [comment]
Hi @xlc, thanks for integrating Acala! 

Your project page has been generated here: https://www.morekudos.com/projects/acala

By default we synchronise and display issues labelled `good-first-issue` on the site. Issues can also be tagged with a `kudos` to have them more prominently displayed. If there any changes you would like to make to the project page, feel free to submit a pull request modifying the Acala JSON file [here](https://github.com/kudos-ink/project-classification/blob/main/data/projects/acala.json), or alternatively you can reopen this issue and edit the details.
