### ISSUE TITLE
[Add a project] Dot Code School

### ISSUE THREAD

**Issue by iammasterbrucewayne** [kudos-ink/project-classification#152]
### Project Name

Dot Code School

### Slug

dotcodeschool

### Description

Dot Code School is an interactive online school that teaches you how to build meaningful web3 applications using the Polkadot SDK.

### Websites

https://dotcodeschool.com/

### Documentation

GitHub README - https://github.com/dotcodeschool/frontend/blob/master/README.md

### Repositories

Dot Code School GitHub - https://github.com/dotcodeschool

### Social Media

X/Twitter - https://x.com/dotcodeschool

### Networks

Polkadot

### Purposes

- [ ] ai
- [ ] bridge
- [ ] dao
- [ ] data
- [ ] defi
- [ ] evm
- [ ] gaming
- [ ] governance
- [ ] nft
- [ ] oracles
- [ ] rwa
- [ ] socialfi
- [ ] staking
- [ ] testing
- [X] universal

### Stack Levels

- [ ] protocol
- [ ] runtime
- [ ] smart-contract
- [ ] messaging
- [X] offchain

### Technologies

Polkadot SDK
Typescript
Rust

### Types

- [X] platform
- [ ] tool
- [ ] library
- [ ] client
- [ ] framework
- [ ] template
- [ ] mobile
- [ ] service
- [ ] dApp

### Rewards

- [ ] The project can pay rewards to contributors.

**Comment by CJ13th** [comment]
Hey @iammasterbrucewayne, thanks for opting to include your project! We currently don't track entire GitHub orgs, only specific repositories. So you will need to let us know which repositories you want to have included. 

e.g
Rust State Machine Tutorial - https://github.com/dotcodeschool/rust-state-machine
Dot Code School - https://github.com/dotcodeschool/frontend
Rust State Machine Tester - https://github.com/dotcodeschool/rust-state-machine-tester

If those look good I can get them added, or feel free to adjust as needed.

**Comment by iammasterbrucewayne** [comment]
Thanks for the detailed info @CJ13th, in that case these repos would be ideal:

Dot Code School - https://github.com/dotcodeschool/frontend
Backend - https://github.com/dotcodeschool/backend
CLI - https://github.com/dotcodeschool/cli

**Comment by CJ13th** [comment]
Hey @iammasterbrucewayne

I've deployed a Hyperbridge project page [morekudos.com/projects/dotcodeschool](https://www.morekudos.com/projects/dotcodeschool)

Going forward, any open issues labelled as `good first issue` from the repos listed on your project page will automatically appear in the table.

We're also running the [The Kudos Carnival ](https://www.morekudos.com/carnival) which is a 6 week issue solving competition with the aim of getting more PBA alumni contributing to the ecosystem, so feel free to label some existing issues or generate new ones. Issues of all types are being requested, some good categories could be:

- Building example Dapps using your team’s SDK or tech stack
- Improving documentation
- Bug fixing
- Polishing existing features / UI
- New feature requests
